### ISSUE TITLE
possible interopability with https://walletconnect.com/ ? 

### ISSUE THREAD

**Issue by grmkris** [nostr-connect/connect#6]
WalletConnect is more used among web3 apps, rather than in bitcoin world.
But it works nicely and is super easy to integrate. I see this connect sdk is following similar principles.

**Comment by tiero** [comment]
Yes, the approach is very similar, although we use Nostr relays and we DO NOT have a centralized part that releases PROJECT_ID.

I don't think Bitcoin world would be that much interested in being compatible and see very little use case to integrate Nostr on the ETH world, do you?

**Comment by grmkris** [comment]
if I remeber correctly the project_id is only needed when you are using their relay instead of deploying your own
https://docs.walletconnect.com/2.0/cloud/relay

Eth world has nostr like projects.. but nostr is more open than them all, that is why I am hacking on nostr... 

I'd love to have a wallet that can: 
- trade and lose money with shitcoins on any chain i want
- use bitcoin over lightning with other bitcoiners
- talk with my friends over nostr 

but I totally understand your point and I agree with it. Just thinking out loud imagining there are no walls among the projects

**Comment by grmkris** [comment]
maybe a better question... could we build WalletConnect clone on top of nostr? I am just speaking nonsense haha, but maybe something will stick and someone gets some inspiration

**Comment by tiero** [comment]
> could we build WalletConnect clone on top of nostr?

I think Nostr Connect could be defined already as the Nostr clone of Wallet Connect built on top Nostr relayers.

I do welcome any effort to try to see how to parasitize Wallet Connect URIs & QRCodes to integrate with Nostr Connect signers, but I am little short on time to do that, would love you try to digging on it and propose me changes eventually.

**Comment by grmkris** [comment]
I'll see you around. Thanks for the great work so far. I love the library
